name: thesis
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.20.1
  - scipy=1.6.1
  - matplotlib=3.3.4
  - pytorch=1.8.0
  - torchvision=0.9.0
  - pillow=8.1.0
  - scikit-image=0.18.1
  - opencv=4.5.1
